/**
 * Stages Microsoft mxc's prebuilt sandbox binary out of `@microsoft/mxc-sdk`'s
 * node_modules and into `packages/less/src/_mxc/`, then generates the
 * `embedded.ts` importer that `bun build --compile` reads to embed the binary
 * into the compiled `boundless`. Mirrors `scripts/build-sandbox-runtime.ts`
 * (which does the same for `just-bash`'s worker assets).
 *
 * Runs from both `postinstall` and the compile step in `scripts/build.ts`, so
 * the generated importer always exists on disk before typecheck or compile.
 *
 * The staged files and the generated `embedded.ts` are gitignored; the
 * committed pieces are this script, the loader (`tools/mxc-runtime.ts`), and
 * the ambient declaration (`tools/mxc-embedded.d.ts`) that lets typecheck pass
 * on a fresh clone before this script has run.
 *
 * mxc ships its binaries under `bin/<arch>/<name>` (arch = arm64 | x64). The
 * SDK's own resolver looks for them at `$MXC_BIN_DIR/<arch>/<name>`, which is
 * the layout the loader recreates at runtime. We stage only the host
 * platform's binary set for the host arch — the compiled binary runs on the
 * machine that built it, so cross-platform embedding would only bloat it.
 */
import { createHash } from "node:crypto";
import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readFileSync,
	readdirSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const SDK_PKG = "@microsoft/mxc-sdk";
const OUT_DIR = join(ROOT, "packages/less/src/_mxc");

/** The mxc binaries the SDK resolver looks for, keyed by host platform. */
function hostBinaryNames(platform: NodeJS.Platform): string[] {
	switch (platform) {
		case "darwin":
			return ["mxc-exec-mac"];
		case "linux":
			return ["lxc-exec"];
		case "win32":
			return [
				"wxc-exec.exe",
				"wxc-windows-sandbox-daemon.exe",
				"wxc-windows-sandbox-guest.exe",
				"winhttp-proxy-shim.exe",
				"wslcsdk.dll",
				"wxc-host-prep.exe",
				"mxc-diagnostic-console.exe",
			];
		default:
			return [];
	}
}

/** mxc's `getSdkArch()` mapping: arm64 stays arm64, everything else → x64. */
function sdkArch(arch: NodeJS.Architecture): string {
	return arch === "arm64" ? "arm64" : "x64";
}

/** Locate the SDK package dir, accounting for Bun's `.bun/` hoist layout. */
function findSdkDir(): string {
	const direct = join(ROOT, "node_modules", SDK_PKG);
	if (existsSync(join(direct, "package.json"))) return direct;

	const bunCache = join(ROOT, "node_modules/.bun");
	if (existsSync(bunCache)) {
		const slug = `${SDK_PKG.replace("/", "+")}@`;
		const entries = readdirSync(bunCache).filter((n) => n.startsWith(slug));
		if (entries.length > 0) {
			const candidate = join(bunCache, entries[0], "node_modules", SDK_PKG);
			if (existsSync(join(candidate, "package.json"))) return candidate;
		}
	}
	throw new Error(`Could not locate ${SDK_PKG} in node_modules. Run \`bun install\` first.`);
}

/**
 * Write `embedded.ts`. When `assets` is empty (no binary for this platform),
 * the importer exports an empty manifest so the loader cleanly no-ops and the
 * SDK falls back to self-resolution / sandbox-unavailable passthrough.
 */
function writeEmbeddedModule(assets: { name: string; arch: string; executable: boolean }[]): void {
	const lines: string[] = [
		"// AUTO-GENERATED by scripts/build-mxc-runtime.ts — do not edit.",
		"// Staged mxc sandbox binaries, embedded into the compiled boundless via",
		'// `with { type: "file" }`. Regenerated on postinstall and build.',
		"",
	];
	assets.forEach((a, i) => {
		lines.push(`import bin${i} from "./${a.arch}/${a.name}.mxcbin" with { type: "file" };`);
	});
	lines.push("");

	// Hash the staged bytes so the loader caches per content version.
	const hash = createHash("sha256");
	for (const a of assets) {
		hash.update(readFileSync(join(OUT_DIR, a.arch, `${a.name}.mxcbin`)));
	}
	const digest = assets.length > 0 ? hash.digest("hex").slice(0, 16) : "none";

	lines.push(`export const MXC_RUNTIME_HASH = ${JSON.stringify(digest)};`);
	lines.push(
		"export const MXC_EMBEDDED_ASSETS: ReadonlyArray<{ name: string; arch: string; executable: boolean; path: string }> = [",
	);
	assets.forEach((a, i) => {
		lines.push(
			`\t{ name: ${JSON.stringify(a.name)}, arch: ${JSON.stringify(a.arch)}, executable: ${a.executable}, path: bin${i} },`,
		);
	});
	lines.push("];");
	lines.push("");
	writeFileSync(join(OUT_DIR, "embedded.ts"), lines.join("\n"));
}

function main(): void {
	const sdkDir = findSdkDir();
	const arch = sdkArch(process.arch);
	const names = hostBinaryNames(process.platform);

	// Reset staged binaries so a stale arch dir can't leak into the build.
	rmSync(OUT_DIR, { recursive: true, force: true });
	mkdirSync(join(OUT_DIR, arch), { recursive: true });

	const staged: { name: string; arch: string; executable: boolean }[] = [];
	for (const name of names) {
		const src = join(sdkDir, "bin", arch, name);
		if (!existsSync(src)) {
			console.warn(`[build-mxc-runtime] ${SDK_PKG} ships no ${arch}/${name}; skipping.`);
			continue;
		}
		copyFileSync(src, join(OUT_DIR, arch, `${name}.mxcbin`));
		// .dll and the like are loaded, not executed; only exec stubs need +x.
		const executable = !name.endsWith(".dll");
		staged.push({ name, arch, executable });
	}

	if (staged.length === 0) {
		console.warn(
			`[build-mxc-runtime] No mxc binaries staged for ${process.platform}/${arch}. Sandboxing will be unavailable in the compiled binary (passthrough).`,
		);
	}
	writeEmbeddedModule(staged);
	console.log(
		`[build-mxc-runtime] Staged ${staged.length} mxc binary(ies) for ${process.platform}/${arch}.`,
	);
}

main();
