#!/usr/bin/env bun
/**
 * Reads the bundled-skill source markdown under
 * packages/agent/src/bundled-skills/<name>/ and generates a TypeScript module
 * (bundled-skills.generated.ts) that embeds each skill's files as strings, so
 * `bun build --compile` can include them in the single binary (no FS at runtime).
 *
 * The generated module is committed and kept in sync by a test
 * (bundled-skills-sync.test.ts). Edit the markdown, then run this script.
 *
 *   bun run scripts/embed-bundled-skills.ts          # regenerate
 *   bun run scripts/embed-bundled-skills.ts --check   # exit 1 if stale
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(SCRIPT_DIR, "..");
export const SOURCE_DIR = join(ROOT, "packages/agent/src/bundled-skills");
export const OUTPUT = join(ROOT, "packages/agent/src/bundled-skills.generated.ts");

const SKILL_NAME_REGEX = /^[a-z0-9]+(-[a-z0-9]+)*$/;

export interface BundledSkillFile {
	path: string;
	content: string;
}

export interface BundledSkill {
	name: string;
	description: string;
	allowedTools: string | null;
	compatibility: string | null;
	files: BundledSkillFile[];
}

/** Parse YAML frontmatter (same shape as packages/agent/src/tools/skill-utils.ts). */
function parseFrontmatter(content: string): { data: Record<string, string>; body: string } | null {
	const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n([\s\S]*))?$/);
	if (!match) return null;
	const data: Record<string, string> = {};
	for (const line of match[1].split(/\r?\n/)) {
		const colonIndex = line.indexOf(":");
		if (colonIndex > 0) {
			data[line.slice(0, colonIndex).trim()] = line.slice(colonIndex + 1).trim();
		}
	}
	return { data, body: match[2] ?? "" };
}

/** Recursively collect every file under `dir`, with paths relative to `dir`. */
function collectFiles(dir: string): BundledSkillFile[] {
	const out: BundledSkillFile[] = [];
	const walk = (current: string): void => {
		for (const entry of readdirSync(current, { withFileTypes: true })) {
			const full = join(current, entry.name);
			if (entry.isDirectory()) {
				walk(full);
			} else if (entry.isFile()) {
				out.push({
					path: relative(dir, full).split(/[\\/]/).join("/"),
					content: readFileSync(full, "utf-8"),
				});
			}
		}
	};
	walk(dir);
	// Deterministic ordering.
	out.sort((a, b) => a.path.localeCompare(b.path));
	return out;
}

/** Load and validate all bundled skills from a source root directory. */
export function loadBundledSkillsFromDir(sourceDir: string): BundledSkill[] {
	const skills: BundledSkill[] = [];
	const dirNames = readdirSync(sourceDir, { withFileTypes: true })
		.filter((e) => e.isDirectory())
		.map((e) => e.name)
		.sort((a, b) => a.localeCompare(b));

	for (const dirName of dirNames) {
		const skillDir = join(sourceDir, dirName);
		const files = collectFiles(skillDir);

		const skillMd = files.find((f) => f.path === "SKILL.md");
		if (!skillMd) {
			throw new Error(`Bundled skill "${dirName}" is missing SKILL.md`);
		}
		const parsed = parseFrontmatter(skillMd.content);
		if (!parsed) {
			throw new Error(`Bundled skill "${dirName}" has invalid SKILL.md frontmatter`);
		}
		const name = parsed.data.name?.trim();
		if (!name) {
			throw new Error(`Bundled skill "${dirName}" SKILL.md is missing a name`);
		}
		if (name !== dirName) {
			throw new Error(
				`Bundled skill directory "${dirName}" does not match frontmatter name "${name}"`,
			);
		}
		if (!SKILL_NAME_REGEX.test(name)) {
			throw new Error(`Bundled skill name "${name}" must match ${SKILL_NAME_REGEX.source}`);
		}
		const description = parsed.data.description?.trim();
		if (!description) {
			throw new Error(`Bundled skill "${dirName}" SKILL.md is missing a description`);
		}

		skills.push({
			name,
			description,
			allowedTools: parsed.data.allowed_tools?.trim() || null,
			compatibility: parsed.data.compatibility?.trim() || null,
			files,
		});
	}
	return skills;
}

/** Render the generated TypeScript module for a set of bundled skills. */
export function renderGeneratedModule(skills: BundledSkill[]): string {
	const lines: string[] = [
		"// Auto-generated by scripts/embed-bundled-skills.ts — do not edit.",
		"// Source: packages/agent/src/bundled-skills/<name>/**",
		"// Regenerate with: bun run scripts/embed-bundled-skills.ts",
		"",
		'import type { BundledSkill } from "./bundled-skills-types";',
		"",
		"export const BUNDLED_SKILLS: BundledSkill[] = [",
	];
	for (const skill of skills) {
		lines.push("\t{");
		lines.push(`\t\tname: ${JSON.stringify(skill.name)},`);
		lines.push(`\t\tdescription: ${JSON.stringify(skill.description)},`);
		lines.push(`\t\tallowedTools: ${JSON.stringify(skill.allowedTools)},`);
		lines.push(`\t\tcompatibility: ${JSON.stringify(skill.compatibility)},`);
		lines.push("\t\tfiles: [");
		for (const file of skill.files) {
			lines.push(
				`\t\t\t{ path: ${JSON.stringify(file.path)}, content: ${JSON.stringify(file.content)} },`,
			);
		}
		lines.push("\t\t],");
		lines.push("\t},");
	}
	lines.push("];", "");
	return lines.join("\n");
}

function main(): void {
	const check = process.argv.includes("--check");
	const skills = loadBundledSkillsFromDir(SOURCE_DIR);
	const rendered = renderGeneratedModule(skills);

	if (check) {
		let existing = "";
		try {
			existing = readFileSync(OUTPUT, "utf-8");
		} catch {
			// missing — treated as stale below
		}
		if (existing !== rendered) {
			console.error(
				"bundled-skills.generated.ts is out of date. Run: bun run scripts/embed-bundled-skills.ts",
			);
			process.exit(1);
		}
		console.log("bundled-skills.generated.ts is up to date.");
		return;
	}

	writeFileSync(OUTPUT, rendered);
	const count = skills.length;
	const fileCount = skills.reduce((n, s) => n + s.files.length, 0);
	console.log(
		`Embedded ${count} bundled skill(s), ${fileCount} file(s) → ${relative(ROOT, OUTPUT)}`,
	);
}

// Run only when invoked directly, not when imported by tests.
if (import.meta.path === Bun.main) {
	main();
}

// Keep statSync referenced for tree-shakers that might flag the import; harmless.
void statSync;
