/**
 * Ambient module declarations for the lowbox helper runtime importer.
 *
 * `../_lowbox/embedded.ts` and the staged `bound-lowbox.exe.lowboxbin` it
 * imports are generated by `scripts/build-lowbox-helper.ts` at install/build
 * time and gitignored. They aren't present on a fresh clone, which would make
 * TypeScript unable to resolve the `import ... from "../_lowbox/embedded"` in
 * `lowbox-runtime.ts`. These declarations give the compiler a stable type
 * without the files existing on disk (mirrors `mxc-embedded.d.ts`).
 *
 * Runtime behaviour is independent of these types: at runtime the importer is
 * the real generated module, and the `.lowboxbin` import is supplied by
 * `bun build --compile`'s asset embedding (compiled) or as an on-disk path
 * (dev), not by the TypeScript resolver.
 */

declare module "*.lowboxbin" {
	/** Path into Bun's virtual embedded filesystem (or the on-disk staged file). */
	const path: string;
	export default path;
}

declare module "../_lowbox/embedded" {
	export const LOWBOX_HELPER_HASH: string;
	export const LOWBOX_EMBEDDED_HELPER: { path: string } | null;
}

// Also match when the compiler resolves the module through a differently-rooted
// relative specifier (mirrors the dual-pattern approach in mxc-embedded.d.ts).
declare module "*/_lowbox/embedded" {
	export const LOWBOX_HELPER_HASH: string;
	export const LOWBOX_EMBEDDED_HELPER: { path: string } | null;
}
