/**
 * Ambient module declarations for the mxc sandbox runtime importer.
 *
 * `../_mxc/embedded.ts` and the staged `*.mxcbin` binaries it imports are
 * generated by `scripts/build-mxc-runtime.ts` at install/build time and
 * gitignored. They aren't present on a fresh clone, which would make
 * TypeScript unable to resolve the `import ... from "../_mxc/embedded"` in
 * `mxc-runtime.ts`. These declarations give the compiler a stable type without
 * the files existing on disk.
 *
 * Runtime behaviour is independent of these types: at runtime the importer is
 * the real generated module, and the `.mxcbin` imports are supplied by
 * `bun build --compile`'s asset embedding (compiled) or as on-disk paths (dev),
 * not by the TypeScript resolver.
 */

declare module "*.mxcbin" {
	/** Path into Bun's virtual embedded filesystem (or the on-disk staged file). */
	const path: string;
	export default path;
}

interface MxcEmbeddedAsset {
	readonly name: string;
	readonly arch: string;
	readonly executable: boolean;
	/** Path to the embedded binary bytes (bunfs in compiled mode, disk in dev). */
	readonly path: string;
}

declare module "../_mxc/embedded" {
	export const MXC_RUNTIME_HASH: string;
	export const MXC_EMBEDDED_ASSETS: ReadonlyArray<MxcEmbeddedAsset>;
}

// Also match when the compiler resolves the module through a differently-rooted
// relative specifier (mirrors the dual-pattern approach in runtime-assets.d.ts).
declare module "*/_mxc/embedded" {
	export const MXC_RUNTIME_HASH: string;
	export const MXC_EMBEDDED_ASSETS: ReadonlyArray<MxcEmbeddedAsset>;
}
