/// <reference path="./mxc-embedded.d.ts" />
/**
 * Runtime materialization of mxc's embedded sandbox binary for a COMPILED
 * boundless, where node_modules isn't on disk and the SDK can't find its own
 * executable. The `embedded.ts` importer (generated by
 * `scripts/build-mxc-runtime.ts`, gitignored) carries the binary bytes via
 * Bun's `with { type: "file" }` embedding. This module writes them out to a
 * stable per-content-hash directory under `~/.bound/less/mxc-runtime/` and
 * points `MXC_BIN_DIR` at it, recreating the `<arch>/<name>` layout the SDK
 * resolver expects.
 *
 * In a dev / source run the importer either carries the host binaries staged
 * at install time (in which case materializing is harmless and uniform) or is
 * empty (in which case this no-ops and the SDK self-resolves from
 * node_modules). Either way the SDK finds a binary the same way in both modes.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { MXC_EMBEDDED_ASSETS, MXC_RUNTIME_HASH } from "../_mxc/embedded";

let ensured = false;

/**
 * Idempotently stage the embedded mxc binary and set `MXC_BIN_DIR`. Safe to
 * call on every spawn / availability check — the first call does the work, the
 * rest return immediately. Respects a pre-set `MXC_BIN_DIR` (operator override)
 * and no-ops when there are no embedded assets.
 */
export function ensureMxcRuntime(): void {
	if (ensured) return;
	ensured = true;

	// Operator already pointed mxc at a binary directory — don't second-guess it.
	if (process.env.MXC_BIN_DIR) return;
	// Nothing embedded (empty importer): the SDK resolves from node_modules.
	if (!MXC_EMBEDDED_ASSETS || MXC_EMBEDDED_ASSETS.length === 0) return;

	const root = join(homedir(), ".bound", "less", "mxc-runtime", MXC_RUNTIME_HASH);
	for (const asset of MXC_EMBEDDED_ASSETS) {
		const dest = join(root, asset.arch, asset.name);
		if (existsSync(dest)) continue;
		mkdirSync(dirname(dest), { recursive: true });
		writeFileSync(dest, readFileSync(asset.path));
		if (asset.executable) {
			try {
				chmodSync(dest, 0o755);
			} catch {
				// Best effort; a read-only FS or odd umask shouldn't be fatal here.
			}
		}
	}
	process.env.MXC_BIN_DIR = root;
}
